---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

dependency:
  name: "galaxy"

driver:
  name: "docker"

platforms:
- name: "CentOS7"
  image: "centos:7"

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: "ansible"
  playbooks:
    converge: "../common/converge.yml"
    verify: "../common/verify.yml"

verifier:
  name: "ansible"

scenario:
  test_sequence:
  - "dependency"
  - "lint"
  - "destroy"
  - "syntax"
  - "create"
  - "prepare"
  - "converge"
  - "idempotence"
  - "verify"
  - "destroy"
